name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: "Hello, World!!!"
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"